name: Run Cucumber Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci  # or use `npm install` if you prefer

      - name: Run generateExcel.ts script
        run: npx ts-node src/utils/generateExcel.ts

      - name: Run Cucumber smoke tests
        run: npx cucumber-js features/PIMCreation.feature --tags "@smoke"

      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-screenshots
          path: test-results/screenshots
