# .github/workflows/cucumber.yml
name: Run Cucumber Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # or your preferred version

      - name: Install dependencies
        run: npm ci  # faster & more reliable in CI

      - name: Run Cucumber smoke tests
        run: npx cucumber-js features/PIMCreation.feature --tags "@smoke"
